spring:
  cloud:
    gateway:
      routes:
      - id: account-service
        uri: lb://account-service
        predicates:
        - Path=/api/account/**
      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/api/customer/** 
        
server:
  port: 9191
  error:
    include-message: always

eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/  

management:
  endpoints:
    web:
      exposure:
        include: "*"
